"""Import every SQLAlchemy model module so Base.metadata is fully populated
before app.db.Base.metadata.create_all() runs at startup."""

from app.models import (  # noqa: F401
    activity_log,
    affiliate_funnel,
    affiliate_link,
    affiliate_niche,
    agent_approval,
    agent_command,
    agent_run,
    analytics_event,
    brand_voice,
    call_record,
    conversion_event,
    credit_profile,
    customer,
    daily_report,
    deal,
    document_record,
    feature_usage,
    follow_up,
    funding_readiness,
    invoice,
    landing_page,
    lead,
    opportunity,
    quote,
    seo_asset,
    social_calendar,
    social_post,
    task,
    voice_script,
    website_project,
)
