"""Import every SQLAlchemy model so it registers on Base.metadata before create_all() runs."""

from app.models import (  # noqa: F401
    activity_log,
    affiliate_funnel,
    affiliate_link,
    affiliate_niche,
    agent_approval,
    agent_command,
    agent_run,
    analytics_event,
    brand_voice,
    conversion_event,
    credit_profile,
    customer,
    daily_report,
    deal,
    document_record,
    feature_usage,
    follow_up,
    funding_readiness,
    landing_page,
    lead,
    seo_asset,
    social_calendar,
    social_post,
    task,
    website_project,
)
