import LegalPageLayout from "./LegalPageLayout";

export default function DisclaimerPage() {
  return (
    <LegalPageLayout title="Disclaimer" updated="July 2026">
      <p>
        PEN2PRO provides education, strategy, organization, and readiness tools. It
        does not guarantee credit repair results, funding approval, loan approval,
        or business success.
      </p>
      <h2 className="text-base font-bold text-white">Not Financial, Legal, or Credit Advice</h2>
      <p>
        Roadmaps, funding-readiness checklists, and credit-readiness guidance
        generated by PEN2PRO are for informational and planning purposes only. They
        are not a substitute for advice from a licensed attorney, accountant,
        financial advisor, or credit counselor.
      </p>
      <h2 className="text-base font-bold text-white">Results Vary</h2>
      <p>
        Every business, credit profile, and financial situation is different.
        Outcomes depend on your effort, market conditions, lender/creditor
        decisions, and factors PEN2PRO does not control. Past results shared on this
        site are individual outcomes, not guarantees of future performance.
      </p>
      <h2 className="text-base font-bold text-white">Affiliate &amp; Partner Links</h2>
      <p>
        Some resources on PEN2PRO (LLC formation, banking, credit, funding, and other
        tools) are affiliate or partner links. We may earn a commission if you use
        them, at no extra cost to you. We only recommend resources we believe are
        useful to founders building a business.
      </p>
      <h2 className="text-base font-bold text-white">Your Responsibility</h2>
      <p>
        You are responsible for verifying information and making your own informed
        decisions before taking financial, legal, or credit-related action.
      </p>
    </LegalPageLayout>
  );
}
