import LegalPageLayout from "./LegalPageLayout";

export default function DisclaimerPage() {
  return (
    <LegalPageLayout title="Disclaimer" updated="August 2026">
      <p className="rounded-lg border border-[#1A2D50] bg-[#0D1528] p-4 text-slate-300">
        PEN2PRO does not guarantee credit repair results, funding approval, loan approval, or business success. The
        platform provides education, strategy, organization, and readiness tools — not financial, legal, credit
        repair, or investment advice.
      </p>

      <h2 className="text-lg font-bold text-white">Educational Purpose</h2>
      <p>
        Roadmaps, checklists, and strategies generated by PEN2PRO's AI engine (RMIE) are educational and
        organizational in nature. They are meant to help you plan and take action — they are not a substitute for
        professional legal, financial, tax, or credit counseling.
      </p>

      <h2 className="text-lg font-bold text-white">Credit &amp; Funding Tools</h2>
      <p>
        Content on the Credit Repair and Funding Readiness pages helps you organize documentation and understand
        general best practices for credit and funding readiness. It does not guarantee a specific credit score
        increase, dispute outcome, vendor approval, or loan/funding decision, all of which are determined by third
        parties outside PEN2PRO's control.
      </p>

      <h2 className="text-lg font-bold text-white">Business Outcomes</h2>
      <p>
        Business success depends on many factors including effort, execution, market conditions, and capital.
        Examples and figures shown on PEN2PRO are illustrative and not a promise of specific results for your
        business.
      </p>

      <h2 className="text-lg font-bold text-white">Affiliate Links</h2>
      <p>
        PEN2PRO may earn a commission from partner links on the Affiliate, Funding, and Credit Repair pages. We only
        recommend services we believe are useful to founders, but you should evaluate any third-party service
        independently before using it.
      </p>
    </LegalPageLayout>
  );
}
