import LegalPageLayout from "../components/legal/LegalPageLayout";

export default function DisclaimerPage() {
  return (
    <LegalPageLayout title="Disclaimer" updated="July 2026">
      <p className="font-bold text-white">
        PEN2PRO does not guarantee credit repair results, funding approval, loan approval,
        or business success. The platform provides education, strategy, organization, and
        readiness tools — not guaranteed outcomes.
      </p>

      <h2 className="font-display text-xl font-bold text-white pt-4">Business &amp; Income</h2>
      <p>
        Roadmaps, blueprints, and strategy plans generated by PEN2PRO's AI (RMIE) are
        planning tools based on the information you provide. They are not a promise of
        revenue, profit, or business success. Every business carries risk, and results
        vary based on effort, market conditions, execution, and factors outside PEN2PRO's
        control.
      </p>

      <h2 className="font-display text-xl font-bold text-white pt-4">Credit &amp; Funding</h2>
      <p>
        Content on the Credit Repair and Funding Readiness pages is educational. PEN2PRO
        is not a credit repair organization, lender, or law firm, and does not perform
        disputes on your behalf or guarantee any change to your credit profile, approval
        for financing, or approval for business credit or loans.
      </p>

      <h2 className="font-display text-xl font-bold text-white pt-4">Affiliate Relationships</h2>
      <p>
        Some links on PEN2PRO (LLC formation, business banking, funding partners, and
        similar services on the Affiliate page) are affiliate links. PEN2PRO may earn a
        commission if you use them, at no extra cost to you. We only link to services we
        believe are useful for building a business — always do your own research before
        signing up.
      </p>

      <h2 className="font-display text-xl font-bold text-white pt-4">Not Professional Advice</h2>
      <p>
        Nothing on PEN2PRO constitutes legal, tax, accounting, or financial advice.
        Consult a qualified professional before making decisions that affect your
        finances, credit, or legal standing.
      </p>
    </LegalPageLayout>
  );
}
