import { useEffect } from "react";
import { Link } from "react-router-dom";
import Navbar from "../components/layout/Navbar";
import Footer from "../components/layout/Footer";

export default function DisclaimerPage() {
  useEffect(() => {
    document.title = "Disclaimer | PEN2PRO";
  }, []);

  return (
    <div className="min-h-screen bg-[#0A0F1E] text-white">
      <Navbar />
      <section className="px-5 py-20">
        <div className="mx-auto max-w-3xl">
          <div className="mb-4 inline-flex items-center gap-2 rounded-full border border-[#1A2D50] bg-[#0F1520] px-4 py-1.5 text-xs font-bold text-[#FF8A00] uppercase tracking-widest">
            Legal
          </div>
          <h1 className="mb-8 font-display text-3xl font-black md:text-4xl">Disclaimer</h1>

          <div className="space-y-5 text-[1.05rem] leading-[1.85] text-slate-300">
            <p>
              PEN2PRO does not guarantee credit repair results, funding approval, loan approval, or
              business success. The platform provides education, strategy, organization, and readiness
              tools — not financial, legal, credit repair, or investment services.
            </p>
            <p>
              Roadmaps, action plans, and strategy output generated by PEN2PRO's AI (RMIE — Rapid
              Monetization Intelligence Engine) are informational guidance based on the details you
              provide. Actual outcomes depend on your effort, market conditions, execution, and factors
              outside PEN2PRO's control.
            </p>
            <p>
              Nothing on this platform should be interpreted as a promise of income, a guarantee of
              approval from any lender, vendor, or credit bureau, or a substitute for advice from a
              licensed attorney, accountant, credit counselor, or financial advisor. Always do your own
              due diligence before making business, credit, or funding decisions.
            </p>
            <p>
              Third-party links (LLC formation, banking, funding, credit, marketing, and other affiliate
              resources) are provided for convenience. PEN2PRO may earn a referral commission from these
              partners and does not control or guarantee their services.
            </p>
          </div>

          <div className="mt-12 flex flex-col gap-3 sm:flex-row">
            <Link to="/funding" className="rounded-xl px-8 py-3.5 text-sm font-black text-[#0A0F1E] btn-gold text-center">
              Funding Readiness
            </Link>
            <Link to="/credit-repair" className="rounded-xl border border-[#1A2D50] px-8 py-3.5 text-sm font-semibold text-slate-300 hover:text-white transition-colors text-center">
              Credit Repair Guide
            </Link>
          </div>
        </div>
      </section>
      <Footer />
    </div>
  );
}
