import { Link } from "react-router-dom";
import Navbar from "../components/layout/Navbar";
import Footer from "../components/layout/Footer";

export default function DisclaimerPage() {
  return (
    <div className="min-h-screen" style={{ background: "#080C14" }}>
      <Navbar />
      <div className="mx-auto max-w-3xl px-5 py-20">
        <p className="text-sm font-bold uppercase tracking-widest text-slate-500 mb-2">Legal</p>
        <h1 className="font-display text-4xl font-black text-white mb-6">Disclaimer</h1>
        <p className="text-slate-500 text-sm mb-10">Last updated: July 2026</p>

        <div className="space-y-8 text-slate-400 leading-7">
          <section className="rounded-xl border p-5" style={{ borderColor: "rgba(255,138,0,0.3)", background: "#0D1528" }}>
            <p className="text-white font-semibold">
              PEN2PRO does not guarantee credit repair results, funding approval, loan approval, or business success.
              The platform provides education, strategy, organization, and readiness tools — not promises of outcome.
            </p>
          </section>

          <section>
            <h2 className="font-display text-xl font-bold text-white mb-2">Business &amp; Income Results</h2>
            <p>
              Roadmaps, launch plans, and growth strategies generated by PEN2PRO's RMIE engine are strategic
              guidance based on the information you provide. Results vary based on effort, market conditions,
              execution, capital, and factors outside PEN2PRO's control. Past results shared by Robert Green or
              other founders are not a guarantee of your results.
            </p>
          </section>

          <section>
            <h2 className="font-display text-xl font-bold text-white mb-2">Credit &amp; Funding Guidance</h2>
            <p>
              Content on the <Link to="/credit-repair" className="text-[#FF8A00] hover:underline">Credit Repair</Link> and{" "}
              <Link to="/funding" className="text-[#FF8A00] hover:underline">Funding Readiness</Link> pages is
              educational and organizational in nature. PEN2PRO is not a credit repair organization, law firm, or
              lender, and does not perform disputes, guarantee score changes, or guarantee loan, grant, or funding
              approval. Always work with licensed professionals for legal, tax, or financial decisions specific to
              your situation.
            </p>
          </section>

          <section>
            <h2 className="font-display text-xl font-bold text-white mb-2">Affiliate Relationships</h2>
            <p>
              Some links on PEN2PRO (LLC formation, banking, funding, domains, tools, and other partners) may be
              affiliate links. PEN2PRO may earn a commission if you use these links, at no extra cost to you. We
              only recommend tools and partners we believe add real value.
            </p>
          </section>

          <section>
            <h2 className="font-display text-xl font-bold text-white mb-2">Not Professional Advice</h2>
            <p>
              Nothing on PEN2PRO constitutes legal, tax, accounting, investment, or financial advice. Consult a
              qualified professional before making decisions that affect your business, credit, or finances.
            </p>
          </section>
        </div>
      </div>
      <Footer />
    </div>
  );
}
