import { useEffect } from "react";
import { Link, useLocation } from "react-router-dom";
import Navbar from "../components/layout/Navbar";
import Footer from "../components/layout/Footer";

const LAST_UPDATED = "July 7, 2026";

const CONTENT = {
  "/privacy": {
    label: "Privacy Policy",
    title: "Privacy Policy",
    intro:
      "This Privacy Policy explains what information PEN2PRO collects, how it is used, and the choices you have. By using PEN2PRO, you agree to the practices described here.",
    sections: [
      {
        heading: "Information We Collect",
        body: "We collect information you provide directly — name, email, phone (optional), business idea details, and waitlist or account information — along with usage data such as pages visited and features used, so we can improve the roadmap and RMIE experience.",
      },
      {
        heading: "How We Use Information",
        body: "We use your information to generate your business roadmap, operate your account, respond to support requests, send relevant product updates, and improve PEN2PRO's AI tools. We do not sell your personal information.",
      },
      {
        heading: "Sharing of Information",
        body: "We may share information with service providers who help us operate the platform (hosting, email, payments, analytics) under confidentiality obligations, or when required by law.",
      },
      {
        heading: "Data Retention & Security",
        body: "We retain account and roadmap data as long as your account is active or as needed to provide services. We use reasonable technical and organizational safeguards, but no system is 100% secure.",
      },
      {
        heading: "Your Choices",
        body: "You may request access to, correction of, or deletion of your personal information at any time by contacting us through the platform.",
      },
    ],
  },
  "/terms": {
    label: "Terms of Service",
    title: "Terms of Service",
    intro:
      "These Terms govern your use of PEN2PRO, the AI-powered Rapid Monetization Intelligence Engine (RMIE) platform. By creating an account or using the platform, you agree to these Terms.",
    sections: [
      {
        heading: "Use of the Platform",
        body: "PEN2PRO provides AI-generated business roadmaps, strategy tools, and educational resources. You agree to use the platform only for lawful purposes and to provide accurate information when building your roadmap or account.",
      },
      {
        heading: "Subscriptions & Payments",
        body: "Pro, Elite, and Founders tiers are billed according to the plan selected at checkout. Subscriptions renew automatically unless canceled. Founders access is offered under the terms presented at time of purchase.",
      },
      {
        heading: "No Guarantee of Results",
        body: "PEN2PRO provides education, strategy, organization, and readiness tools. PEN2PRO does not guarantee income, business success, credit repair results, funding approval, or loan approval. Outcomes depend on individual effort, market conditions, and factors outside our control.",
      },
      {
        heading: "Intellectual Property",
        body: "The PEN2PRO platform, brand, and content are owned by PEN2PRO. Roadmaps generated for your account are yours to use for your own business purposes.",
      },
      {
        heading: "Termination",
        body: "We may suspend or terminate accounts that violate these Terms or misuse the platform. You may cancel your subscription at any time.",
      },
    ],
  },
  "/disclaimer": {
    label: "Disclaimer",
    title: "Disclaimer",
    intro:
      "PEN2PRO is an education, strategy, and business-readiness platform. Please read this disclaimer carefully before relying on any roadmap, plan, or guidance generated by the platform.",
    sections: [
      {
        heading: "Not Financial, Legal, or Credit Repair Advice",
        body: "Content generated by PEN2PRO — including business roadmaps, funding readiness checklists, and credit readiness guidance — is for educational and organizational purposes only. It is not financial, legal, tax, or credit repair advice. Consult a licensed professional before making financial or legal decisions.",
      },
      {
        heading: "No Guaranteed Outcomes",
        body: "PEN2PRO does not guarantee income, funding approval, loan approval, credit score improvement, or business success. Every situation is different, and results depend on individual effort, execution, market conditions, and factors beyond our control.",
      },
      {
        heading: "AI-Generated Content",
        body: "Roadmaps and strategy output are generated using AI and should be reviewed with your own judgment. Verify details such as legal requirements, licensing, and financial figures before acting on them.",
      },
      {
        heading: "Affiliate & Partner Links",
        body: "PEN2PRO may share links to third-party partners for services like LLC formation, business banking, or funding. We may receive compensation for these referrals. We do not control and are not responsible for third-party services.",
      },
    ],
  },
};

export default function LegalPage() {
  const { pathname } = useLocation();
  const page = CONTENT[pathname] || CONTENT["/privacy"];

  useEffect(() => {
    document.title = `${page.title} | PEN2PRO`;
  }, [page.title]);

  return (
    <div className="min-h-screen" style={{ background: "#080C14" }}>
      <Navbar />
      <div className="mx-auto max-w-3xl px-5 py-16 md:py-20">
        <p className="text-sm font-bold uppercase tracking-widest text-slate-500 mb-2">Legal</p>
        <h1 className="font-display text-4xl font-black text-white mb-3 md:text-5xl">{page.title}</h1>
        <p className="text-xs text-slate-600 mb-8">Last updated: {LAST_UPDATED}</p>
        <p className="text-slate-400 text-lg leading-8 mb-10">{page.intro}</p>

        <div className="space-y-8">
          {page.sections.map((s) => (
            <div key={s.heading}>
              <h2 className="text-xl font-bold text-white mb-2">{s.heading}</h2>
              <p className="text-slate-400 leading-7">{s.body}</p>
            </div>
          ))}
        </div>

        <div className="mt-14 flex flex-wrap gap-4 border-t border-[#1A2D50] pt-8">
          <Link to="/privacy" className="text-sm font-semibold text-slate-400 hover:text-[#FF8A00]">Privacy</Link>
          <Link to="/terms" className="text-sm font-semibold text-slate-400 hover:text-[#FF8A00]">Terms</Link>
          <Link to="/disclaimer" className="text-sm font-semibold text-slate-400 hover:text-[#FF8A00]">Disclaimer</Link>
          <Link to="/" className="text-sm font-semibold text-slate-400 hover:text-[#FF8A00]">Back Home</Link>
        </div>
      </div>
      <Footer />
    </div>
  );
}
