import { Link } from "react-router-dom";
import Navbar from "../components/layout/Navbar";
import Footer from "../components/layout/Footer";

const LAST_UPDATED = "July 2026";

const CONTENT = {
  privacy: {
    eyebrow: "Legal",
    title: "Privacy Policy",
    intro:
      "PEN2PRO (“we,” “us,” “our”) respects your privacy. This policy explains what information we collect, how we use it, and the choices you have.",
    sections: [
      {
        heading: "Information We Collect",
        body: "When you use PEN2PRO, we may collect information you provide directly, including your name, email address, phone number, business idea details, and roadmap intake answers. We also collect basic usage data (pages visited, features used) to improve the platform.",
      },
      {
        heading: "How We Use Your Information",
        body: "We use your information to generate your business roadmap, manage your account and subscription tier, respond to support requests, send you updates about PEN2PRO (including waitlist and launch communications), and improve our AI-generated recommendations.",
      },
      {
        heading: "Data Sharing",
        body: "We do not sell your personal information. We may share data with service providers who help us operate PEN2PRO (such as payment processing and hosting), and only to the extent necessary for them to perform those services.",
      },
      {
        heading: "Data Security",
        body: "We use reasonable technical and administrative safeguards to protect your information. No system is completely secure, so we cannot guarantee absolute security.",
      },
      {
        heading: "Your Choices",
        body: "You can request access to, correction of, or deletion of your personal information at any time by contacting us. You can also unsubscribe from marketing emails using the link in any message.",
      },
    ],
  },
  terms: {
    eyebrow: "Legal",
    title: "Terms of Service",
    intro:
      "These Terms govern your use of PEN2PRO, the AI-powered RMIE (Rapid Monetization Intelligence Engine) platform. By using PEN2PRO, you agree to these Terms.",
    sections: [
      {
        heading: "The Service",
        body: "PEN2PRO provides AI-generated business roadmaps, strategy guidance, funding and credit readiness education, and related tools. Free, Pro, Elite, and Founders tiers unlock different levels of access, described on our Pricing page.",
      },
      {
        heading: "No Guarantee of Results",
        body: "PEN2PRO provides education, strategy, organization, and readiness tools. We do not guarantee income, business success, funding approval, loan approval, or credit repair results. Outcomes depend on your effort, market conditions, and factors outside our control.",
      },
      {
        heading: "Your Responsibilities",
        body: "You agree to provide accurate information, use PEN2PRO for lawful purposes, and make your own final decisions about legal, financial, tax, and business formation matters — consulting a licensed professional where appropriate.",
      },
      {
        heading: "Subscriptions & Billing",
        body: "Pro and Elite plans are billed on a recurring basis as described at checkout. You may cancel at any time; access continues through the end of the current billing period. Founders offers are limited-availability and priced as shown at time of purchase.",
      },
      {
        heading: "Limitation of Liability",
        body: "To the fullest extent permitted by law, PEN2PRO is not liable for indirect, incidental, or consequential damages arising from your use of the platform.",
      },
    ],
  },
  disclaimer: {
    eyebrow: "Legal",
    title: "Disclaimer",
    intro:
      "PEN2PRO is an education, strategy, and readiness platform. Please read this disclaimer carefully before relying on any roadmap, plan, or recommendation generated by PEN2PRO.",
    sections: [
      {
        heading: "No Guarantee of Outcomes",
        body: "PEN2PRO does not guarantee credit repair results, funding approval, loan approval, or business success. The platform provides education, strategy, organization, and readiness tools — not promises of a specific result.",
      },
      {
        heading: "Not Legal, Financial, or Tax Advice",
        body: "Nothing on PEN2PRO constitutes legal, financial, tax, or credit repair advice. Always consult a licensed attorney, accountant, or financial professional before making business, legal, or financial decisions.",
      },
      {
        heading: "AI-Generated Content",
        body: "Roadmaps, strategies, and recommendations are generated with AI assistance based on the information you provide. Review all output critically and adapt it to your specific situation before acting on it.",
      },
      {
        heading: "Individual Results Vary",
        body: "Results depend on individual effort, market conditions, industry, location, and factors beyond PEN2PRO's control. Testimonials or examples referenced on this site are not a guarantee of similar outcomes for every user.",
      },
    ],
  },
};

export default function LegalPage({ type }) {
  const data = CONTENT[type];

  return (
    <div className="min-h-screen bg-[#0A0F1E] text-white">
      <Navbar />

      <section className="px-5 py-20">
        <div className="mx-auto max-w-3xl">
          <div className="mb-4 inline-flex items-center gap-2 rounded-full border border-[#1A2D50] bg-[#0F1520] px-4 py-1.5 text-xs font-bold text-[#FF8A00] uppercase tracking-widest">
            {data.eyebrow}
          </div>
          <h1 className="mb-3 font-display text-4xl font-black leading-tight md:text-5xl">{data.title}</h1>
          <p className="mb-10 text-sm text-slate-500">Last updated: {LAST_UPDATED}</p>

          <p className="mb-10 text-lg leading-relaxed text-slate-300">{data.intro}</p>

          <div className="space-y-8">
            {data.sections.map((s) => (
              <div key={s.heading} className="rounded-2xl border border-[#1A2D50] bg-[#0F1520] p-6">
                <h2 className="mb-2 font-display text-xl font-black text-white">{s.heading}</h2>
                <p className="text-sm leading-relaxed text-slate-400">{s.body}</p>
              </div>
            ))}
          </div>

          <div className="mt-12 rounded-2xl border border-[#1A2D50] bg-[#0F1520] p-6 text-center">
            <p className="mb-4 text-sm text-slate-400">Questions about these policies?</p>
            <Link
              to="/about"
              className="rounded-xl px-6 py-3 text-sm font-black text-[#0A0F1E] btn-gold inline-block"
            >
              Contact PEN2PRO
            </Link>
          </div>
        </div>
      </section>

      <Footer />
    </div>
  );
}
