import { Link, useLocation } from "react-router-dom";
import Navbar from "../components/layout/Navbar";
import Footer from "../components/layout/Footer";

const CONTENT = {
  "/privacy": {
    title: "Privacy Policy",
    intro:
      "This Privacy Policy explains how PEN2PRO collects, uses, and protects the information you share with us when you use the platform.",
    sections: [
      {
        heading: "Information We Collect",
        body: "We collect information you provide directly — such as your name, email, phone number, and business idea details — when you create an account, request a roadmap, or join the waitlist. We also collect basic usage data (pages visited, features used) to improve the product.",
      },
      {
        heading: "How We Use Your Information",
        body: "We use your information to generate your business roadmap, communicate with you about your account and PEN2PRO updates, improve our AI tools, and, where you've opted in, share relevant funding, credit, and affiliate resources.",
      },
      {
        heading: "How We Protect Your Information",
        body: "We use industry-standard safeguards to protect your data. We do not sell your personal information. We may share data with trusted service providers (such as payment processors or hosting providers) solely to operate the platform.",
      },
      {
        heading: "Your Choices",
        body: "You can request access to, correction of, or deletion of your personal data at any time by contacting us. You can unsubscribe from marketing emails using the link in any message we send.",
      },
    ],
  },
  "/terms": {
    title: "Terms of Service",
    intro:
      "By creating an account or using PEN2PRO, you agree to the following terms. Please read them carefully.",
    sections: [
      {
        heading: "Use of the Platform",
        body: "PEN2PRO provides AI-generated business roadmaps, strategy tools, and educational resources. You agree to use the platform for lawful purposes and to provide accurate information when completing intake forms.",
      },
      {
        heading: "No Guarantee of Results",
        body: "PEN2PRO does not guarantee income, funding approval, credit repair outcomes, or business success. Roadmaps, checklists, and strategy output are educational tools, not professional legal, financial, or credit-repair advice. Results depend on your own effort, market conditions, and factors outside our control.",
      },
      {
        heading: "Subscriptions & Billing",
        body: "Pro, Elite, and Founders plans are billed on the cadence shown at checkout. You may cancel at any time; access continues through the end of the current billing period. Founders pricing, where offered, is locked in for the life of an active account.",
      },
      {
        heading: "Account Responsibility",
        body: "You are responsible for maintaining the confidentiality of your account credentials and for all activity under your account.",
      },
      {
        heading: "Changes to These Terms",
        body: "We may update these Terms from time to time. Continued use of PEN2PRO after changes are posted constitutes acceptance of the updated Terms.",
      },
    ],
  },
  "/disclaimer": {
    title: "Disclaimer",
    intro:
      "PEN2PRO is a business strategy and education platform. Please read this disclaimer before acting on any roadmap, checklist, or recommendation generated by the platform.",
    sections: [
      {
        heading: "Not Financial, Legal, or Credit Repair Advice",
        body: "PEN2PRO does not provide licensed financial, legal, tax, or credit-repair advice. Content is provided for general education and planning purposes only. Consult a qualified professional (attorney, CPA, licensed credit counselor, or financial advisor) before making significant business, legal, or financial decisions.",
      },
      {
        heading: "No Guaranteed Outcomes",
        body: "PEN2PRO does not guarantee income, business success, funding approval, loan approval, or specific credit score improvements. Every roadmap is a starting strategy — outcomes depend on execution, market conditions, and factors beyond our control.",
      },
      {
        heading: "Third-Party Resources",
        body: "PEN2PRO may link to third-party vendors, lenders, or affiliate partners (LLC formation services, banking, credit tools, funding partners, and similar). We may earn a commission from some of these links. We do not control and are not responsible for third-party terms, pricing, or outcomes.",
      },
    ],
  },
};

export default function LegalPage() {
  const { pathname } = useLocation();
  const page = CONTENT[pathname] || CONTENT["/terms"];

  return (
    <div className="min-h-screen" style={{ background: "#080C14" }}>
      <Navbar />
      <div className="mx-auto max-w-3xl px-5 py-16">
        <p className="text-sm font-bold uppercase tracking-widest text-slate-500 mb-2">Legal</p>
        <h1 className="font-display text-4xl font-black text-white mb-6">{page.title}</h1>
        <p className="text-slate-400 text-lg mb-10 leading-7">{page.intro}</p>

        <div className="space-y-8">
          {page.sections.map((s) => (
            <div key={s.heading}>
              <h2 className="text-xl font-bold text-white mb-2">{s.heading}</h2>
              <p className="text-slate-400 leading-7">{s.body}</p>
            </div>
          ))}
        </div>

        <div className="mt-14 rounded-xl border p-5" style={{ borderColor: "rgba(255,138,0,0.3)", background: "#0D1528" }}>
          <p className="text-sm text-slate-400">
            Questions about this page? Reach out any time, or head back to{" "}
            <Link to="/" className="text-[#FF8A00] hover:underline">the homepage</Link> or your{" "}
            <Link to="/dashboard" className="text-[#FF8A00] hover:underline">dashboard</Link>.
          </p>
        </div>
      </div>
      <Footer />
    </div>
  );
}
