import { Link } from "react-router-dom";
import Navbar from "../components/layout/Navbar";
import Footer from "../components/layout/Footer";

const SECTIONS = [
  {
    title: "Acceptance of Terms",
    body: "By accessing or using PEN2PRO, you agree to be bound by these Terms of Service. If you do not agree with any part of these terms, you may not use the platform.",
  },
  {
    title: "Platform Description",
    body: "PEN2PRO is an AI-powered business development platform — the Rapid Monetization Intelligence Engine (RMIE) — that helps users turn ideas, skills, and lived experience into business roadmaps, launch strategies, and execution plans. PEN2PRO is an educational and organizational tool, not a licensed business, legal, financial, or credit counseling service.",
  },
  {
    title: "User Accounts",
    body: "You are responsible for maintaining the security of your account credentials. You agree not to share your login information and to notify us immediately of any unauthorized account access. PEN2PRO reserves the right to suspend or terminate accounts that violate these terms.",
  },
  {
    title: "Acceptable Use",
    body: "You agree to use PEN2PRO only for lawful purposes. You may not use the platform to generate content intended to defraud, harm, or deceive others; to distribute spam or malicious code; or to scrape, copy, or resell platform content without written permission.",
  },
  {
    title: "Subscription & Payment",
    body: "Paid plans (Pro, Elite, Founders) are billed as described at checkout. All fees are non-refundable unless otherwise stated. You may cancel your subscription at any time, and access will continue through the end of your billing period. Founders Lifetime is a one-time payment with no recurring fees.",
  },
  {
    title: "AI-Generated Content",
    body: "Roadmaps, plans, scripts, and other content generated by PEN2PRO's AI system are for informational and planning purposes only. The platform does not guarantee the accuracy, completeness, or fitness of AI-generated content for any specific use case. Users are responsible for independently verifying information before acting on it.",
  },
  {
    title: "No Professional Advice",
    body: "PEN2PRO does not provide legal, financial, accounting, tax, credit repair, or investment advice. Nothing on the platform should be construed as professional advice. Always consult a licensed professional before making significant business, financial, or legal decisions.",
  },
  {
    title: "Intellectual Property",
    body: "All PEN2PRO branding, platform design, proprietary AI systems, and content are the intellectual property of PEN2PRO and Robert Earl Green Jr. You may not reproduce, distribute, or create derivative works without written consent.",
  },
  {
    title: "Limitation of Liability",
    body: "PEN2PRO and its founders, employees, and partners shall not be liable for any indirect, incidental, consequential, or punitive damages arising from your use of the platform. Total liability for any claim shall not exceed the amount you paid to PEN2PRO in the 12 months preceding the claim.",
  },
  {
    title: "Termination",
    body: "We reserve the right to terminate or suspend your access to PEN2PRO at any time, with or without notice, for violations of these terms or other conduct we determine to be harmful to the platform, other users, or our mission.",
  },
  {
    title: "Changes to Terms",
    body: "We may update these Terms of Service from time to time. Continued use of PEN2PRO after updates constitutes acceptance of the revised terms. We will notify active users of material changes via email.",
  },
  {
    title: "Governing Law",
    body: "These terms are governed by the laws of the State of Texas. Any disputes shall be resolved in the courts of Harris County, Texas.",
  },
];

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-[#080C14] text-white">
      <Navbar />

      <div className="mx-auto max-w-3xl px-5 py-20">
        <div className="mb-10">
          <div className="mb-4 inline-flex items-center gap-2 rounded-full border border-[#1A2D50] bg-[#0F1520] px-4 py-1.5 text-xs font-bold text-[#1E88E5] uppercase tracking-widest">
            Legal
          </div>
          <h1 className="font-display text-4xl font-black text-white">Terms of Service</h1>
          <p className="mt-3 text-sm text-slate-500">Effective Date: June 1, 2026</p>
          <p className="mt-4 text-slate-400 leading-relaxed">
            These Terms of Service govern your use of PEN2PRO. By using the platform, you agree to these terms in full.
          </p>
        </div>

        <div className="space-y-8">
          {SECTIONS.map((s) => (
            <div key={s.title} className="rounded-2xl border border-[#1A2D50] bg-[#0F1520] p-6">
              <h2 className="mb-3 font-bold text-white text-lg">{s.title}</h2>
              <p className="text-sm text-slate-400 leading-relaxed">{s.body}</p>
            </div>
          ))}
        </div>

        <div className="mt-12 rounded-2xl border border-[#1A2D50] bg-[#0F1520] p-6 text-center">
          <p className="text-sm text-slate-400">
            Questions about these terms?{" "}
            <a href="mailto:legal@pen2pro.com" className="text-[#1E88E5] hover:underline font-semibold">
              legal@pen2pro.com
            </a>
          </p>
          <div className="mt-4 flex flex-col items-center gap-2 sm:flex-row sm:justify-center">
            <Link to="/privacy" className="text-sm text-slate-400 hover:text-white transition-colors">Privacy Policy</Link>
            <span className="hidden sm:inline text-slate-600">·</span>
            <Link to="/disclaimer" className="text-sm text-slate-400 hover:text-white transition-colors">Disclaimer</Link>
            <span className="hidden sm:inline text-slate-600">·</span>
            <Link to="/" className="text-sm text-[#FF8A00] hover:underline font-semibold">Back to Home</Link>
          </div>
        </div>
      </div>

      <Footer />
    </div>
  );
}
