import { Link } from "react-router-dom";
import Navbar from "../components/layout/Navbar";
import Footer from "../components/layout/Footer";

const SECTIONS = [
  {
    title: "1. Acceptance of Terms",
    body: "By accessing or using PEN2PRO (the \"Platform\"), you agree to these Terms of Service. If you do not agree, do not use the Platform.",
  },
  {
    title: "2. What PEN2PRO Provides",
    body: "PEN2PRO is an AI-powered RMIE (Rapid Monetization Intelligence Engine) that generates business roadmaps, strategy guidance, and organizational tools based on the information you provide. Output is generated by AI and should be reviewed with your own judgment and, where appropriate, a licensed professional.",
  },
  {
    title: "3. Accounts & Eligibility",
    body: "You must provide accurate information when creating an account or joining the waitlist. You are responsible for maintaining the confidentiality of your login credentials and for all activity under your account.",
  },
  {
    title: "4. Subscriptions & Billing",
    body: "Pro, Elite, and Founders plans are billed according to the pricing shown at checkout. Subscriptions renew automatically until canceled. You may cancel at any time; cancellation stops future billing but does not refund past charges except where required by law.",
  },
  {
    title: "5. Acceptable Use",
    body: "You agree not to misuse the Platform — including attempting to disrupt service, reverse-engineer the AI systems, or use generated content for unlawful purposes.",
  },
  {
    title: "6. No Guarantee of Results",
    body: "PEN2PRO provides education, strategy, organization, and readiness tools. We do not guarantee income, business success, credit repair results, loan approval, or funding approval. Results depend on individual effort, execution, and market conditions.",
  },
  {
    title: "7. Intellectual Property",
    body: "The Platform, its design, and underlying technology belong to PEN2PRO. Roadmaps and content generated for your account are yours to use for your own business purposes.",
  },
  {
    title: "8. Limitation of Liability",
    body: "PEN2PRO is provided \"as is\" without warranties of any kind. To the fullest extent permitted by law, PEN2PRO is not liable for indirect, incidental, or consequential damages arising from use of the Platform.",
  },
  {
    title: "9. Changes to These Terms",
    body: "We may update these Terms as the Platform evolves. Continued use after changes take effect means you accept the updated Terms.",
  },
];

export default function TermsPage() {
  return (
    <div className="min-h-screen" style={{ background: "#080C14" }}>
      <Navbar />

      <div className="border-b border-[#1A2235]" style={{ background: "#0F1520" }}>
        <div className="mx-auto max-w-4xl px-5 py-16 text-center">
          <div className="inline-flex items-center gap-2 rounded-full border border-[#D4A017]/30 bg-[#D4A017]/10 px-4 py-1.5 text-xs font-semibold text-[#D4A017] mb-6">
            LEGAL
          </div>
          <h1 className="font-display text-4xl font-black text-white md:text-5xl mb-4">
            Terms of <span className="gradient-text">Service</span>
          </h1>
          <p className="text-slate-400 text-sm">Effective date: January 1, 2026</p>
        </div>
      </div>

      <div className="mx-auto max-w-4xl px-5 py-16">
        <p className="text-slate-400 text-sm leading-7 mb-10">
          These Terms of Service govern your use of PEN2PRO. Please read them carefully before using the Platform.
        </p>

        <div className="space-y-8">
          {SECTIONS.map((s) => (
            <div key={s.title} className="rounded-2xl border border-[#1A2235] p-6" style={{ background: "#0F1520" }}>
              <h2 className="font-display text-lg font-bold text-white mb-3">{s.title}</h2>
              <p className="text-sm text-slate-400 leading-7">{s.body}</p>
            </div>
          ))}
        </div>

        <div className="mt-10 rounded-xl border border-[#1A2235] p-5" style={{ background: "#0F1520" }}>
          <p className="text-xs text-slate-500 leading-6">
            Questions about these Terms? Contact us through the{" "}
            <Link to="/waitlist" className="text-[#FF8A00] hover:underline">waitlist form</Link> and we'll follow up.
          </p>
        </div>
      </div>

      <Footer />
    </div>
  );
}
