import { Link } from "react-router-dom";
import Navbar from "../components/layout/Navbar";
import Footer from "../components/layout/Footer";

const SECTIONS = [
  {
    title: "Acceptance of Terms",
    body: `By accessing or using PEN2PRO ("the Platform"), you agree to be bound by these Terms of Service ("Terms"). If you do not agree to all the Terms, you may not use the Platform. These Terms apply to all visitors, users, and others who access or use PEN2PRO.`,
  },
  {
    title: "Description of Service",
    body: `PEN2PRO is an AI-powered Rapid Monetization Intelligence Engine (RMIE) that helps users generate business roadmaps, strategy plans, and execution guides based on their ideas and goals. The Platform offers free, paid subscription, and lifetime access tiers.\n\nThe outputs generated by PEN2PRO are for informational and planning purposes only. They do not constitute legal, financial, accounting, or professional advice.`,
  },
  {
    title: "Account Registration",
    body: `To access certain features, you must create an account. You agree to provide accurate, current, and complete information during registration. You are responsible for maintaining the confidentiality of your login credentials and for all activity that occurs under your account.\n\nYou must be at least 18 years old to create an account and use the Platform.`,
  },
  {
    title: "Subscription Plans and Payment",
    body: `PEN2PRO offers multiple subscription tiers including Free, Pro, Elite, and Founders Lifetime. Paid subscriptions are billed through Stripe. By providing payment information, you authorize PEN2PRO to charge your payment method for the applicable subscription fee.\n\nMonthly subscriptions may be cancelled at any time. Cancellation takes effect at the end of the current billing period. The Founders Lifetime plan is a one-time payment and is non-refundable once access has been granted.\n\nPEN2PRO reserves the right to modify pricing with reasonable advance notice.`,
  },
  {
    title: "Intellectual Property",
    body: `The Platform, including its content, features, and functionality, is owned by PEN2PRO and is protected by copyright, trademark, and other intellectual property laws.\n\nThe AI-generated roadmaps, strategies, and business plans produced for your account are provided for your personal or business use. You may not resell or redistribute platform outputs as your own commercial product without written permission.`,
  },
  {
    title: "User Conduct",
    body: `You agree not to: use the Platform for any unlawful purpose; attempt to gain unauthorized access to any portion of the Platform; use automated tools to scrape, harvest, or copy Platform content; impersonate any person or entity; or interfere with the proper functioning of the Platform.\n\nPEN2PRO reserves the right to suspend or terminate accounts that violate these Terms.`,
  },
  {
    title: "Disclaimers and Limitations",
    body: `PEN2PRO does not guarantee business success, income, funding approval, credit improvement, or any specific outcome from using the Platform. The AI-generated content is informational and based on the information you provide.\n\nTHE PLATFORM IS PROVIDED "AS IS" WITHOUT WARRANTIES OF ANY KIND, EXPRESS OR IMPLIED. TO THE MAXIMUM EXTENT PERMITTED BY LAW, PEN2PRO DISCLAIMS ALL WARRANTIES AND SHALL NOT BE LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, OR PUNITIVE DAMAGES.`,
  },
  {
    title: "Third-Party Links and Affiliate Relationships",
    body: `The Platform may contain links to third-party websites, tools, and services. Some of these links may be affiliate links, meaning PEN2PRO may earn a commission if you make a purchase through them. This does not affect the price you pay.\n\nPEN2PRO does not endorse or assume responsibility for third-party content, products, or services.`,
  },
  {
    title: "Governing Law",
    body: `These Terms shall be governed by and construed in accordance with the laws of the State of Texas, without regard to its conflict of law provisions. Any dispute arising from these Terms shall be resolved in the courts of Harris County, Texas.`,
  },
  {
    title: "Changes to These Terms",
    body: `We may revise these Terms at any time. We will notify you of material changes by posting the updated Terms on the Platform. Your continued use of PEN2PRO after changes are posted constitutes your acceptance of the revised Terms.`,
  },
  {
    title: "Contact",
    body: `For questions about these Terms, contact us at: support@pen2pro.com`,
  },
];

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-[#080C14] text-white">
      <Navbar />
      <div className="mx-auto max-w-3xl px-5 py-20">
        <div className="mb-10">
          <div className="mb-4 inline-flex items-center gap-2 rounded-full border border-[#1A2D50] bg-[#0F1520] px-4 py-1.5 text-xs font-bold uppercase tracking-widest text-[#FF8A00]">
            Legal
          </div>
          <h1 className="mb-3 font-display text-4xl font-black">Terms of Service</h1>
          <p className="text-sm text-slate-500">Effective Date: June 1, 2026 | Last Updated: June 1, 2026</p>
          <p className="mt-4 text-slate-400 leading-relaxed">
            Please read these Terms of Service carefully before using the PEN2PRO platform. These Terms govern your access to and use of our services.
          </p>
        </div>

        <div className="space-y-8">
          {SECTIONS.map((s) => (
            <div key={s.title} className="rounded-2xl border border-[#1A2D50] bg-[#0F1520] p-6">
              <h2 className="mb-3 font-bold text-white text-lg">{s.title}</h2>
              {s.body.split("\n\n").map((para, i) => (
                <p key={i} className="mb-3 text-sm text-slate-400 leading-relaxed last:mb-0">{para}</p>
              ))}
            </div>
          ))}
        </div>

        <div className="mt-12 flex flex-wrap gap-4 border-t border-[#1A2D50] pt-8">
          <Link to="/privacy" className="text-sm text-[#1E88E5] hover:underline">Privacy Policy</Link>
          <Link to="/disclaimer" className="text-sm text-[#1E88E5] hover:underline">Disclaimer</Link>
          <Link to="/" className="text-sm text-slate-400 hover:text-white">← Back to Home</Link>
        </div>
      </div>
      <Footer />
    </div>
  );
}
